{{- $ingress := .Values.fairspace.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fairspace.name" . }}-ingress
{{- with $ingress.annotations.pluto }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "fairspace.name" . }}
    {{- include "fairspace.labels" . | nindent 4 }}
spec:
{{- if $ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ template "pluto.hostname" $ }}
      secretName: {{ template "fairspace.tlsSecretName" $ }}
{{- end }}
  rules:
    - host: {{ template "pluto.hostname" $ }}
      http:
        paths:
          - path: /
            pathType: {{ $ingress.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
  {{- end -}}
